const express = require('express');
const router = express.Router();
const deployService = require('../services/deployService');
const logger = require('../logger');

router.post('/deploy', async (req, res) => {
  try {
    const { projectPath, target, options } = req.body;
    if (!projectPath || !target) {
      return res.status(400).json({ success: false, error: 'projectPath and target are required' });
    }

    logger.info(`[Deploy] Starting deployment to ${target} for ${projectPath}`);

    const result = await deployService.deploy(projectPath, target, options || {});
    
    logger.info(`[Deploy] Deployment to ${target} successful: ${result.url}`);
    res.json({ success: true, result });
  } catch (err) {
    logger.error('[Deploy] Deployment failed:', err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

router.get('/targets', async (req, res) => {
  try {
    const targets = deployService.getAvailableTargets();
    res.json({ success: true, targets });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

router.post('/validate', async (req, res) => {
  try {
    const { target, options } = req.body;
    if (!target) {
      return res.status(400).json({ success: false, error: 'target is required' });
    }

    const adapter = deployService.adapters[target];
    if (!adapter) {
      return res.status(400).json({ success: false, error: `Unknown target: ${target}` });
    }

    const valid = await adapter.validateOptions(options || {});
    res.json({ success: true, valid });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

const fs = require('fs');
const path = require('path');
const { ZipArchive } = require('archiver');

// ── 1-Click ZIP Project Exporter with Launcher ─────────────────────────────────
router.post('/export-zip', async (req, res) => {
  try {
    const { projectPath, projectName = 'ai-dost-project' } = req.body;
    if (!projectPath || !fs.existsSync(projectPath)) {
      return res.status(400).json({ success: false, error: 'Valid projectPath is required' });
    }

    const safeName = projectName.replace(/[^a-zA-Z0-9_-]/g, '_');
    const zipFilename = `${safeName}.zip`;

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${zipFilename}"`);

    const archive = new ZipArchive({ zlib: { level: 9 } });

    archive.on('error', (err) => {
      logger.error('[Deploy] Zip export archive error:', err.message);
      if (!res.headersSent) res.status(500).json({ success: false, error: err.message });
    });

    archive.pipe(res);

    // Inject 1-click Windows start launcher
    archive.append(`@echo off
echo ========================================================
echo  🚀 Starting ${projectName} (Generated by AI-Dost)
echo ========================================================
echo.
if not exist node_modules (
  echo [1/2] Installing dependencies...
  call npm install
)
echo.
echo [2/2] Starting Development Server...
call npm run dev
pause
`, { name: 'start-windows.bat' });

    // Inject 1-click Mac/Linux start launcher
    archive.append(`#!/bin/bash
echo "========================================================"
echo " 🚀 Starting ${projectName} (Generated by AI-Dost)"
echo "========================================================"
echo ""
if [ ! -d "node_modules" ]; then
  echo "[1/2] Installing dependencies..."
  npm install
fi
echo ""
echo "[2/2] Starting Development Server..."
npm run dev
`, { name: 'start-mac-linux.sh', mode: 0o755 });

    // Append project directory (ignore node_modules, .git, temp caches)
    archive.glob('**/*', {
      cwd: projectPath,
      ignore: ['node_modules/**', '.git/**', '.next/**', 'dist/**', 'build/**', '*.log']
    });

    await archive.finalize();
    logger.info(`[Deploy] Exported ZIP for ${projectName} (${projectPath})`);
  } catch (err) {
    logger.error('[Deploy] Export ZIP failed:', err.message);
    if (!res.headersSent) res.status(500).json({ success: false, error: err.message });
  }
});

module.exports = router;