/**
 * AI-Dost Document Engine — chat se Word (.docx), PowerPoint (.pptx), CSV/Excel files.
 * Flow: LLM (cascade) content generate karta hai → file build → /downloads/ me save → URL return.
 */
const express = require('express');
const logger = require('../logger');
const router = express.Router();
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DOWNLOADS_DIR = path.join(__dirname, '../../frontend/public/downloads');
fs.mkdirSync(DOWNLOADS_DIR, { recursive: true });
const BASE = `http://127.0.0.1:${process.env.PORT || 5000}`;

// ── LLM content via full cascade (2 attempts) ──────────────────────────────
async function llmContent(systemPrompt, userPrompt, timeoutMs = 120000) {
    // systemPrompt is the template with {TOPIC} placeholder; userPrompt is the actual topic
    const prompt = systemPrompt.replace('{TOPIC}', userPrompt);
    const body = {
        message: prompt,
        model: 'auto',
        mode: 'chat',
        section: 'document',
    };
    for (let attempt = 1; attempt <= 2; attempt++) {
        try {
            const res = await fetch(`${BASE}/api/v1/chat`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(body),
                signal: AbortSignal.timeout(timeoutMs),
            });
            const data = await res.json();
            const content = data.reply || data.message || '';
            if (content && content.length >= 30) return content;
            logger.warn(`📄 LLM attempt ${attempt} empty content`);
        } catch (e) {
            logger.warn(`📄 LLM attempt ${attempt} error: ${e.message}`);
        }
    }
    throw new Error('All AI providers busy — template fallback');
}

// ── Template fallback (LLM fail ho to bhi file mile) ───────────────────────
function templateContent(type, topic) {
    const t = topic.length > 80 ? topic.slice(0, 80) + '...' : topic;
    if (type === 'pptx') {
        return JSON.stringify({
            title: t,
            slides: [
                { title: 'Introduction', points: ['Topic ka parichay', 'Mukhya vishay aur scope', 'Is presentation me kya milega', 'Key questions'] },
                { title: 'Overview', points: ['Sabse important facts', 'Historical background', 'Current status', 'Relevance aaj ke liye'] },
                { title: 'Key Section 1', points: ['Detail 1 - facts ke saath', 'Detail 2', 'Detail 3', 'Aakhri point'] },
                { title: 'Key Section 2', points: ['Detail 1', 'Detail 2', 'Detail 3', 'Aakhri point'] },
                { title: 'Key Section 3', points: ['Detail 1', 'Detail 2', 'Detail 3', 'Aakhri point'] },
                { title: 'Challenges', points: ['Mukhya challenges', 'Solutions', 'Agla step', 'Kya improve ho sakta hai'] },
                { title: 'Future Outlook', points: ['Trends', 'Opportunities', 'Prediction', 'Action items'] },
                { title: 'Conclusion', points: ['Summary - 3 main takeaways', 'Key message', 'Questions?'] },
            ],
        });
    }
    if (type === 'csv') {
        return `Topic,Category,Detail\n${t},Overview,AI-Dost ne ye data generate kiya\n${t},Fact 1,Thodi der me dobara try karo - AI providers busy the\n${t},Fact 2,Regenerate karke full data pao\n${t},Fact 3,AI-Dost Document Engine\n${t},Note,Topic: ${t}`;
    }
    // docx / pdf — markdown
    return `# ${t}\n\n## Overview\n- ${t} ka samagra parichay\n- Mukhya facts aur figures\n- Aaj ke liye relevance\n\n## History & Background\n- Historical context\n- Key milestones\n- Important personalities\n\n## Current Status\n- Latest situation\n- Key developments\n- Statistics\n\n## Challenges\n- Main challenges\n- Solutions\n\n## Future Outlook\n- Trends\n- Opportunities\n- Conclusion\n\n*Generated by AI-Dost — thodi der baad dobara generate karke aur detail pao.*`;
}

// ── Word (.docx) ───────────────────────────────────────────────────────────
async function buildDocx(markdown, title, filename) {
    const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = require('docx');

    const children = [];
    children.push(new Paragraph({
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: title, bold: true, size: 40, color: '1C2030' })],
        spacing: { after: 300 },
    }));

    for (const rawLine of markdown.split('\n')) {
        const line = rawLine.trim();
        if (!line) continue;

        // Bold inline **text** → TextRuns
        const runs = [];
        const parts = line.split(/\*\*(.+?)\*\*/g);
        for (let i = 0; i < parts.length; i++) {
            if (!parts[i]) continue;
            runs.push(new TextRun({ text: parts[i], bold: i % 2 === 1 }));
        }

        if (line.startsWith('### ')) {
            children.push(new Paragraph({ heading: HeadingLevel.HEADING_3, children: runs, spacing: { before: 200, after: 100 } }));
        } else if (line.startsWith('## ')) {
            children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: runs, spacing: { before: 260, after: 120 } }));
        } else if (line.startsWith('# ')) {
            children.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: runs, spacing: { before: 320, after: 160 } }));
        } else if (/^[-*•] /.test(line)) {
            children.push(new Paragraph({
                bullet: { level: 0 },
                children: runs,
                spacing: { after: 60 },
            }));
        } else if (/^\d+\. /.test(line)) {
            children.push(new Paragraph({
                numbering: { reference: 'ordered-list', level: 0 },
                children: runs,
                spacing: { after: 60 },
            }));
        } else {
            children.push(new Paragraph({ children: runs, spacing: { after: 120 } }));
        }
    }

    const doc = new Document({
        numbering: { config: [{ reference: 'ordered-list', levels: [{ level: 0, format: 'decimal', text: '%1.', alignment: 'left' }] }] },
        styles: {
            default: { document: { run: { font: 'Calibri', size: 22 } } },
        },
        sections: [{ children }],
    });

    const buffer = await Packer.toBuffer(doc);
    const filePath = path.join(DOWNLOADS_DIR, filename);
    fs.writeFileSync(filePath, buffer);
    return filename;
}

// ── PDF (reuse existing pdf.js → python pdfGenerator.py) ───────────────────
async function buildPdf(markdown, title, filename) {
    const res = await fetch(`${BASE}/api/pdf/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title, content: markdown }),
        signal: AbortSignal.timeout(60000),
    });
    const data = await res.json();
    if (!data.success || !data.downloadUrl) throw new Error(data.error || 'PDF build failed');
    return data.filename;
}

// ── PowerPoint (.pptx) ─────────────────────────────────────────────────────
async function buildPptx(deckJson, title, filename) {
    const pptxgen = require('pptxgenjs');
    const pptx = new pptxgen();
    pptx.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 });
    pptx.layout = 'WIDE';
    pptx.author = 'AI-Dost';
    pptx.subject = title;

    const ACCENT = '4B8BFC';
    const DARK = '1C2030';

    // Title slide
    const s0 = pptx.addSlide();
    s0.background = { color: DARK };
    s0.addText(title, { x: 0.8, y: 2.3, w: 11.7, h: 1.8, fontSize: 40, bold: true, color: 'FFFFFF', align: 'center', fontFace: 'Segoe UI' });
    s0.addText('AI-Dost Presentation', { x: 0.8, y: 4.3, w: 11.7, h: 0.6, fontSize: 16, color: ACCENT, align: 'center' });

    const slides = (deckJson.slides || []).slice(0, 14);
    for (const [idx, s] of slides.entries()) {
        const slide = pptx.addSlide();
        slide.background = { color: 'FFFFFF' };
        slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.33, h: 0.16, fill: { color: ACCENT } });
        slide.addText(s.title || `Slide ${idx + 1}`, { x: 0.7, y: 0.45, w: 11.9, h: 0.9, fontSize: 28, bold: true, color: DARK, fontFace: 'Segoe UI' });
        const points = (s.points || []).map(p => ({ text: p, options: { bullet: true, color: '333333', fontSize: 18, breakLine: true, paraSpaceAfter: 10 } }));
        slide.addText(points, { x: 0.9, y: 1.6, w: 11.5, h: 5.3, valign: 'top', fontFace: 'Segoe UI' });
    }

    await pptx.writeFile({ fileName: path.join(DOWNLOADS_DIR, filename) });
    // v4 API: fileName (capital N) — lib file seedha destination pe likhta hai
    const filePath = path.join(DOWNLOADS_DIR, filename);
    if (!fs.existsSync(filePath) || fs.statSync(filePath).size < 1000) {
        throw new Error('PPTX file write failed');
    }
    return filename;
}

// ── CSV ────────────────────────────────────────────────────────────────────
function buildCsv(csvText, filename) {
    const cleaned = String(csvText).replace(/```csv\s*/gi, '').replace(/```\s*/g, '').trim();
    // Ensure header + at least 3 rows
    const rows = cleaned.split('\n').filter(r => r.trim().length > 1);
    if (rows.length < 4) throw new Error('CSV content too short');
    const filePath = path.join(DOWNLOADS_DIR, filename);
    fs.writeFileSync(filePath, '\uFEFF' + cleaned + '\n', 'utf-8'); // BOM → Excel me Hindi theek dikhe
    return filename;
}

// ── Parse JSON from LLM output ─────────────────────────────────────────────
function extractJson(content) {
    const cleaned = String(content).replace(/```json\s*/gi, '').replace(/```\s*/g, '').trim();
    const start = cleaned.indexOf('{');
    const end = cleaned.lastIndexOf('}');
    if (start === -1 || end === -1 || end <= start) throw new Error('No JSON found');
    return JSON.parse(cleaned.slice(start, end + 1));
}

// Structured prompts with strong guardrails — compact but specific. Keeps LLM on topic.
const PROMPTS = {
    pdf: `Write a detailed Markdown report ONLY about: {TOPIC}.
Rules:
- Title as "# {TOPIC}"
- Sections with "## " headings: Overview, History/Background, Key Facts, Current Status, Challenges, Conclusion
- Use "- " bullets with concrete facts, figures, dates, names
- Language: match topic (Hindi/Hinglish/English). No fluff.
- DO NOT write about anything else. No generic disclaimers.
- Length: 800-1500 words. Valid Markdown only.`,
    docx: `Write a detailed Markdown report ONLY about: {TOPIC}.
Rules:
- Title as "# {TOPIC}"
- Sections with "## " headings: Overview, History/Background, Key Facts, Current Status, Challenges, Conclusion
- Use "- " bullets with concrete facts, figures, dates, names
- Language: match topic (Hindi/Hinglish/English). No fluff.
- DO NOT write about anything else. No generic disclaimers.
- Length: 800-1500 words. Valid Markdown only.`,
    pptx: `Return ONLY valid JSON for an 8-10 slide deck about: {TOPIC}.
Schema: {"title": "{TOPIC}", "slides": [{"title": "...", "points": ["pt1","pt2","pt3","pt4"]}, ...]}
Rules:
- Slide 1: Introduction. Slides 2-7: Key sections with 4-5 fact-rich points each. Slide 8: Challenges. Slide 9: Future. Slide 10: Conclusion.
- Points: max 15 words, concrete facts. Language matches topic.
- DO NOT include anything except the JSON. No markdown fences.`,
    csv: `Return ONLY CSV (header + 15-25 data rows) about: {TOPIC}. No markdown, no commentary.
Columns: relevant to topic (e.g., for martyrs: Name,Rank,Regiment,Date,Place,State).
First row = headers. No commas inside fields. Language: match topic.`,
    xlsx: `Return ONLY JSON for Excel columns and sample rows about: {TOPIC}.
Schema: {"columns": ["col1","col2",...], "rows": [["val1","val2",...], ...]}
Rules:
- Columns: relevant to topic (martyrs: Name,Rank,Regiment,Date,Place,State,Conflict).
- 15-25 rows of realistic sample data.
- DO NOT include anything except the JSON. No markdown fences.`,
};

const TYPE_EXT = { docx: '.docx', pptx: '.pptx', csv: '.csv', pdf: '.pdf', xlsx: '.xlsx' };

router.post('/generate', async (req, res) => {
    const { type, topic, title } = req.body;
    const t = (type || '').toLowerCase();
    if (!PROMPTS[t]) return res.status(400).json({ success: false, error: 'type must be docx | pptx | csv | pdf | xlsx' });
    if (!topic || !topic.trim()) return res.status(400).json({ success: false, error: 'Topic required' });

    try {
        const safeTitle = (title || topic).trim().slice(0, 60);
        let content;
        try {
            content = await llmContent(PROMPTS[t], topic);
            // Quality check: ensure content is actually about the topic
            const topicKeywords = topic.toLowerCase().split(/\s+/).filter(w => w.length > 3);
            const hasTopic = topicKeywords.some(kw => content.toLowerCase().includes(kw));
            if (!hasTopic && topicKeywords.length > 0) {
                logger.warn(`📄 LLM content off-topic (no ${topicKeywords.join(',')} found) → template fallback`);
                throw new Error('Content quality check failed');
            }
            logger.info(`📄 LLM content ready for ${t} (${content.length} chars)`);
        } catch (e) {
            logger.warn(`📄 LLM unavailable/off-topic → template fallback: ${e.message}`);
            content = templateContent(t, topic);
        }
        const fileId = crypto.randomUUID().substring(0, 8);
        const filename = `${safeTitle.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').slice(0, 40)}_${fileId}${TYPE_EXT[t]}`;

        let finalName;
        if (t === 'pdf') {
            finalName = await buildPdf(content, safeTitle, filename);
        } else if (t === 'docx') {
            finalName = await buildDocx(content, safeTitle, filename);
        } else if (t === 'pptx') {
            const deck = extractJson(content);
            if (!Array.isArray(deck.slides) || deck.slides.length < 3) throw new Error('Not enough slides generated');
            finalName = await buildPptx(deck, deck.title || safeTitle, filename);
        } else if (t === 'xlsx') {
            // xlsx: call python engine for real Excel generation
            const PythonEngine = require('../services/pythonEngineService');
            const xlsxResult = await PythonEngine.xlsxGenerate(topic, safeTitle);
            if (!xlsxResult.ok) throw new Error(xlsxResult.error || 'XLSX generation failed');
            // Copy file from temp to downloads
            const fs = require('fs');
            const path = require('path');
            const src = xlsxResult.data.file_path;
            const dest = path.join(DOWNLOADS_DIR, filename);
            fs.copyFileSync(src, dest);
            finalName = filename;
        } else {
            finalName = buildCsv(content, filename);
        }

        logger.info(`📄 ${t.toUpperCase()} generated: ${finalName}`);
        res.json({
            success: true,
            type: t,
            downloadUrl: `/downloads/${finalName}`,
            filename: finalName,
            message: `${t.toUpperCase()} file ready!`,
        });
    } catch (e) {
        logger.error(`Document generation (${t}) error:`, e.message);
        res.status(500).json({ success: false, error: `Document generation failed: ${e.message}` });
    }
});

module.exports = router;