'use strict';

/**
 * AI-Dost 2.0 — Phase 5A: AuthSynthesizer
 * 
 * Synthesizes production-hardened full-stack authentication files:
 * - Backend routes, middleware, and cryptographic utilities
 * - Database migration scripts for users and refresh_tokens
 * - Frontend AuthContext (in-memory access token, single-flight refresh)
 * - Frontend login/registration forms and ProtectedRoute
 * - Automated security & integration test suite
 */

const crypto = require('crypto');
const path = require('path');
const fs = require('fs');

class AuthSynthesizer {
  /**
   * Synthesize all authentication artifacts for a project
   * @param {Object} plan AuthPlan instance
   * @param {string} workspaceRoot
   * @returns {Map<string, string>} Relative path -> file content
   */
  static synthesize(plan, workspaceRoot) {
    const files = new Map();

    // 1. Backend Cryptographic Utility (Self-contained, zero-external-deps)
    files.set('backend/utils/auth.js', this._generateAuthUtils(plan));

    // 2. Backend Middleware
    files.set('backend/middleware/auth.js', this._generateAuthMiddleware(plan));

    // 3. Backend Routes
    files.set('backend/routes/auth.js', this._generateAuthRoutes(plan));

    // 4. Database Migration
    files.set('backend/migrations/002_create_auth_tables.sql', this._generateAuthMigration(plan));

    // 5. Frontend Auth Context (In-memory storage, single-flight refresh mutex)
    files.set('frontend/src/context/AuthContext.jsx', this._generateFrontendAuthContext(plan));

    // 6. Frontend Accessible Login Form
    files.set('frontend/src/components/LoginForm.jsx', this._generateLoginForm(plan));

    // 7. Frontend Accessible Register Form
    files.set('frontend/src/components/RegisterForm.jsx', this._generateRegisterForm(plan));

    // 8. Frontend Route Guard
    files.set('frontend/src/components/ProtectedRoute.jsx', this._generateProtectedRoute(plan));

    // 9. Automated Test Suite
    files.set('backend/tests/auth.test.js', this._generateAuthTestSuite(plan));

    return files;
  }

  /**
   * Detect conflicts with pre-existing user-authored files
   * @param {string} workspaceRoot
   * @param {Map<string, string>} proposedFiles
   * @returns {{ hasConflict: boolean, conflicts: Array<{ path: string, reason: string }> }}
   */
  static detectConflicts(workspaceRoot, proposedFiles) {
    const conflicts = [];
    for (const relPath of proposedFiles.keys()) {
      const fullPath = path.resolve(workspaceRoot, relPath);
      if (fs.existsSync(fullPath)) {
        // If file already exists, flag conflict to protect user's code
        conflicts.push({
          path: relPath,
          reason: 'Pre-existing user-authored file would be overwritten'
        });
      }
    }
    return {
      hasConflict: conflicts.length > 0,
      conflicts
    };
  }

  static _generateAuthUtils(plan) {
    return `'use strict';
/**
 * Auto-generated by AI-Dost 2.0 Auth Gate (Phase 5A)
 * Cryptographic Password Hashing & HS256 JWT Utilities
 */
const crypto = require('crypto');

const JWT_SECRET = process.env.JWT_SECRET || '${crypto.randomBytes(32).toString('hex')}';
const ISSUER = '${plan.jwt.issuer}';
const AUDIENCE = '${plan.jwt.audience}';
const ACCESS_TTL_SEC = ${plan.jwt.accessTokenTtlSec};

function base64urlEncode(buf) {
  return Buffer.from(buf).toString('base64').replace(/=/g, '').replace(/\\+/g, '-').replace(/\\//g, '_');
}

function base64urlDecode(str) {
  let s = str.replace(/-/g, '+').replace(/_/g, '/');
  while (s.length % 4 !== 0) s += '=';
  return Buffer.from(s, 'base64').toString('utf8');
}

// Pre-computed dummy hash for constant-time evaluation on missing user
const DUMMY_SALT = crypto.randomBytes(16).toString('hex');
const DUMMY_KEY = crypto.scryptSync('dummy_entropy_constant_time', DUMMY_SALT, 64, { cost: 16384, blockSize: 8, parallelization: 1, maxmem: 33554432 }).toString('hex');
const DUMMY_HASH = \`$scrypt$v=1$N=16384,r=8,p=1$\${DUMMY_SALT}$\${DUMMY_KEY}\`;

function hashPassword(password) {
  if (typeof password !== 'string' || Buffer.byteLength(password, 'utf8') > 72) {
    throw new Error('Password must be a string <= 72 bytes');
  }
  const salt = crypto.randomBytes(16).toString('hex');
  const derivedKey = crypto.scryptSync(password, salt, 64, { cost: 16384, blockSize: 8, parallelization: 1, maxmem: 33554432 });
  return \`$scrypt$v=1$N=16384,r=8,p=1$\${salt}$\${derivedKey.toString('hex')}\`;
}

function verifyPassword(password, storedHash) {
  if (typeof password !== 'string' || typeof storedHash !== 'string' || Buffer.byteLength(password, 'utf8') > 72) {
    return false;
  }
  const parts = storedHash.split('$');
  if (parts.length === 6 && parts[1] === 'scrypt') {
    const salt = parts[4];
    const expected = Buffer.from(parts[5], 'hex');
    const derived = crypto.scryptSync(password, salt, expected.length, { cost: 16384, blockSize: 8, parallelization: 1, maxmem: 33554432 });
    return crypto.timingSafeEqual(derived, expected);
  }
  return false;
}

function dummyVerifyPassword(password) {
  verifyPassword(password || 'dummy', DUMMY_HASH);
  return false;
}

function signJwt(payload, secret = JWT_SECRET, expiresInSec = ACCESS_TTL_SEC) {
  const now = Math.floor(Date.now() / 1000);
  const header = { alg: 'HS256', typ: 'JWT' };
  const claims = {
    ...payload,
    iat: now,
    exp: now + expiresInSec,
    jti: crypto.randomUUID(),
    iss: ISSUER,
    aud: AUDIENCE
  };
  const encHeader = base64urlEncode(JSON.stringify(header));
  const encPayload = base64urlEncode(JSON.stringify(claims));
  const sig = crypto.createHmac('sha256', secret).update(\`\${encHeader}.\${encPayload}\`).digest();
  return \`\${encHeader}.\${encPayload}.\${base64urlEncode(sig)}\`;
}

function verifyJwt(token, secret = JWT_SECRET) {
  if (!token || typeof token !== 'string') return { valid: false, error: 'Token missing' };
  const parts = token.trim().split('.');
  if (parts.length !== 3) return { valid: false, error: 'Malformed token' };

  try {
    const header = JSON.parse(base64urlDecode(parts[0]));
    if (header.alg !== 'HS256') return { valid: false, error: 'Rejected unapproved algorithm' };
    const payload = JSON.parse(base64urlDecode(parts[1]));
    const expectedSig = crypto.createHmac('sha256', secret).update(\`\${parts[0]}.\${parts[1]}\`).digest();
    let givenSig;
    let s = parts[2].replace(/-/g, '+').replace(/_/g, '/');
    while (s.length % 4 !== 0) s += '=';
    givenSig = Buffer.from(s, 'base64');
    if (givenSig.length !== expectedSig.length || !crypto.timingSafeEqual(givenSig, expectedSig)) {
      return { valid: false, error: 'Signature mismatch' };
    }
    const now = Math.floor(Date.now() / 1000);
    if (now >= payload.exp) return { valid: false, error: 'Token expired' };
    return { valid: true, payload };
  } catch (err) {
    return { valid: false, error: err.message };
  }
}

module.exports = {
  hashPassword,
  verifyPassword,
  dummyVerifyPassword,
  signJwt,
  verifyJwt,
  JWT_SECRET,
  ISSUER,
  AUDIENCE
};
`;
  }

  static _generateAuthMiddleware(plan) {
    return `'use strict';
/**
 * Auto-generated by AI-Dost 2.0 Auth Gate (Phase 5A)
 * Auth Middleware with Role and Ownership Protection
 */
const { verifyJwt } = require('../utils/auth');

function authenticate(req, res, next) {
  const header = req.headers.authorization || req.headers.Authorization;
  if (!header || !header.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Authentication required: missing or invalid Bearer token' });
  }
  const token = header.substring(7).trim();
  const verified = verifyJwt(token);
  if (!verified.valid) {
    return res.status(401).json({ error: verified.error });
  }
  req.user = verified.payload;
  next();
}

function requireRole(role) {
  const levels = { admin: 100, user: 10, guest: 1 };
  return (req, res, next) => {
    if (!req.user) return res.status(401).json({ error: 'Authentication required' });
    const userLevel = levels[req.user.role] || 0;
    const reqLevel = levels[role] || 0;
    if (userLevel < reqLevel) {
      return res.status(403).json({ error: \`Access denied: requires \${role} role\` });
    }
    next();
  };
}

function requireOwnership(getOwnerId) {
  return async (req, res, next) => {
    if (!req.user) return res.status(401).json({ error: 'Authentication required' });
    if (req.user.role === 'admin') return next(); // Admin override
    try {
      const ownerId = await getOwnerId(req);
      if (!ownerId) return res.status(404).json({ error: 'Resource not found' });
      if (ownerId !== req.user.sub && ownerId !== req.user.id) {
        return res.status(403).json({ error: 'Access denied: ownership mismatch' });
      }
      next();
    } catch {
      return res.status(500).json({ error: 'Failed to verify ownership' });
    }
  };
}

module.exports = {
  authenticate,
  requireRole,
  requireOwnership
};
`;
  }

  static _generateAuthRoutes(plan) {
    return `'use strict';
/**
 * Auto-generated by AI-Dost 2.0 Auth Gate (Phase 5A)
 * Complete Auth API Routes: register, login, refresh, logout, logout-all, me
 */
const express = require('express');
const crypto = require('crypto');
const { hashPassword, verifyPassword, dummyVerifyPassword, signJwt } = require('../utils/auth');
const { authenticate } = require('../middleware/auth');

const router = express.Router();

// In-memory token & user store (synchronized with database in production)
const users = new Map(); // email -> user
const refreshTokens = new Map(); // tokenHash -> { userId, familyId, expiresAt, revokedAt }

// ── 1. REGISTER ─────────────────────────────────────────────────────────────
router.post('/register', (req, res) => {
  const { email, password, name } = req.body || {};
  if (!email || typeof email !== 'string' || !email.includes('@')) {
    return res.status(400).json({ error: 'Valid email is required' });
  }
  if (!password || typeof password !== 'string' || password.length < 8 || Buffer.byteLength(password, 'utf8') > 72) {
    return res.status(400).json({ error: 'Password must be between 8 and 72 bytes' });
  }

  const normEmail = email.toLowerCase().trim();
  if (users.has(normEmail)) {
    return res.status(409).json({ error: 'User already exists' });
  }

  // Anti-mass assignment: role is ALWAYS forced to default 'user'
  const user = {
    id: 'usr_' + crypto.randomUUID(),
    email: normEmail,
    name: typeof name === 'string' ? name.trim() : '',
    passwordHash: hashPassword(password),
    role: 'user',
    status: 'active',
    tokenVersion: 1,
    createdAt: new Date().toISOString()
  };

  users.set(normEmail, user);
  res.status(201).json({
    message: 'User registered successfully',
    user: { id: user.id, email: user.email, name: user.name, role: user.role }
  });
});

// ── 2. LOGIN ────────────────────────────────────────────────────────────────
router.post('/login', (req, res) => {
  const { email, password } = req.body || {};
  if (!email || !password) {
    return res.status(400).json({ error: 'Email and password are required' });
  }

  const normEmail = String(email).toLowerCase().trim();
  const user = users.get(normEmail);

  if (!user) {
    dummyVerifyPassword(password); // Preserve constant-time execution
    return res.status(401).json({ error: 'Invalid credentials' });
  }

  const passwordValid = verifyPassword(password, user.passwordHash);
  if (!passwordValid) {
    return res.status(401).json({ error: 'Invalid credentials' });
  }

  if (user.status !== 'active') {
    return res.status(403).json({ error: 'Account suspended' });
  }

  // Issue short-lived access token
  const accessToken = signJwt({
    sub: user.id,
    email: user.email,
    role: user.role,
    tokenVersion: user.tokenVersion
  });

  // Issue opaque refresh token
  const rawRefreshToken = crypto.randomBytes(32).toString('hex');
  const tokenHash = crypto.createHash('sha256').update(rawRefreshToken).digest('hex');
  const familyId = 'fam_' + crypto.randomUUID();

  refreshTokens.set(tokenHash, {
    userId: user.id,
    familyId,
    expiresAt: Date.now() + (${plan.jwt.refreshTtlSec} * 1000),
    revokedAt: null
  });

  // Set HttpOnly refresh cookie & secure CSRF cookie
  res.cookie('refreshToken', rawRefreshToken, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'Strict',
    path: '/api/auth',
    maxAge: ${plan.jwt.refreshTtlSec} * 1000
  });

  res.cookie('csrfToken', crypto.randomBytes(16).toString('hex'), {
    httpOnly: false,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'Strict',
    path: '/'
  });

  res.json({
    accessToken,
    user: { id: user.id, email: user.email, name: user.name, role: user.role }
  });
});

// ── 3. REFRESH (With Replay & Theft Detection) ──────────────────────────────
router.post('/refresh', (req, res) => {
  const rawToken = req.cookies?.refreshToken || req.body?.refreshToken;
  if (!rawToken) {
    return res.status(401).json({ error: 'Missing refresh token' });
  }

  const tokenHash = crypto.createHash('sha256').update(rawToken).digest('hex');
  const record = refreshTokens.get(tokenHash);

  if (!record) {
    return res.status(401).json({ error: 'Invalid refresh token' });
  }

  // REPLAY ATTACK DETECTION
  if (record.revokedAt !== null) {
    // Revoke entire family lineage!
    for (const [hash, rec] of refreshTokens.entries()) {
      if (rec.familyId === record.familyId) {
        rec.revokedAt = Date.now();
      }
    }
    return res.status(401).json({ error: 'Refresh token reuse detected: session revoked' });
  }

  if (Date.now() >= record.expiresAt) {
    record.revokedAt = Date.now();
    return res.status(401).json({ error: 'Refresh token expired' });
  }

  // Mark old token consumed
  record.revokedAt = Date.now();

  // Find user
  let targetUser = null;
  for (const u of users.values()) {
    if (u.id === record.userId) { targetUser = u; break; }
  }

  if (!targetUser || targetUser.status !== 'active') {
    return res.status(403).json({ error: 'User inactive' });
  }

  // Issue rotated token
  const newRawRefreshToken = crypto.randomBytes(32).toString('hex');
  const newTokenHash = crypto.createHash('sha256').update(newRawRefreshToken).digest('hex');

  refreshTokens.set(newTokenHash, {
    userId: targetUser.id,
    familyId: record.familyId,
    expiresAt: Date.now() + (${plan.jwt.refreshTtlSec} * 1000),
    revokedAt: null
  });

  const newAccessToken = signJwt({
    sub: targetUser.id,
    email: targetUser.email,
    role: targetUser.role,
    tokenVersion: targetUser.tokenVersion
  });

  res.cookie('refreshToken', newRawRefreshToken, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'Strict',
    path: '/api/auth',
    maxAge: ${plan.jwt.refreshTtlSec} * 1000
  });

  res.json({ accessToken: newAccessToken });
});

// ── 4. LOGOUT ───────────────────────────────────────────────────────────────
router.post('/logout', (req, res) => {
  const rawToken = req.cookies?.refreshToken;
  if (rawToken) {
    const tokenHash = crypto.createHash('sha256').update(rawToken).digest('hex');
    const record = refreshTokens.get(tokenHash);
    if (record) record.revokedAt = Date.now();
  }
  res.clearCookie('refreshToken', { path: '/api/auth' });
  res.clearCookie('csrfToken', { path: '/' });
  res.json({ message: 'Logged out' });
});

// ── 5. LOGOUT ALL ───────────────────────────────────────────────────────────
router.post('/logout-all', authenticate, (req, res) => {
  for (const u of users.values()) {
    if (u.id === req.user.sub) {
      u.tokenVersion += 1;
      break;
    }
  }
  for (const rec of refreshTokens.values()) {
    if (rec.userId === req.user.sub) rec.revokedAt = Date.now();
  }
  res.clearCookie('refreshToken', { path: '/api/auth' });
  res.clearCookie('csrfToken', { path: '/' });
  res.json({ message: 'All sessions revoked' });
});

// ── 6. ME ───────────────────────────────────────────────────────────────────
router.get('/me', authenticate, (req, res) => {
  res.json({ user: req.user });
});

module.exports = router;
`;
  }

  static _generateAuthMigration(plan) {
    return `-- Auto-generated by AI-Dost 2.0 Auth Gate (Phase 5A)
-- Canonical Users & Refresh Tokens Schema Migration

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  username TEXT UNIQUE,
  password_hash TEXT NOT NULL,
  hash_algorithm TEXT NOT NULL DEFAULT 'scrypt',
  hash_version INTEGER NOT NULL DEFAULT 1,
  role TEXT NOT NULL DEFAULT 'user',
  status TEXT NOT NULL DEFAULT 'active',
  token_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  family_id TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  revoked_at TEXT,
  replaced_by_token_id TEXT,
  created_at TEXT NOT NULL,
  user_agent_hash TEXT,
  ip_subnet TEXT
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family ON refresh_tokens(family_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens(user_id);
`;
  }

  static _generateFrontendAuthContext(plan) {
    return `import React, { createContext, useContext, useState, useEffect, useRef } from 'react';

const AuthContext = createContext(null);

export function AuthProvider({ children }) {
  // Security Invariant: Access token is stored strictly in-memory (never in persistent client storage)
  const [accessToken, setAccessToken] = useState(null);
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);

  // Single-flight refresh mutex to prevent concurrent refresh requests
  const refreshPromiseRef = useRef(null);

  const refreshToken = async () => {
    if (refreshPromiseRef.current) {
      return refreshPromiseRef.current;
    }

    refreshPromiseRef.current = (async () => {
      try {
        const res = await fetch('/api/auth/refresh', {
          method: 'POST',
          credentials: 'same-origin'
        });
        if (res.ok) {
          const data = await res.json();
          setAccessToken(data.accessToken);
          return data.accessToken;
        } else {
          setAccessToken(null);
          setUser(null);
          return null;
        }
      } catch {
        setAccessToken(null);
        setUser(null);
        return null;
      } finally {
        refreshPromiseRef.current = null;
      }
    })();

    return refreshPromiseRef.current;
  };

  const login = async (email, password) => {
    const res = await fetch('/api/auth/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
      credentials: 'same-origin'
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: 'Login failed' }));
      throw new Error(err.error || 'Login failed');
    }
    const data = await res.json();
    setAccessToken(data.accessToken);
    setUser(data.user);
    return data.user;
  };

  const logout = async () => {
    try {
      await fetch('/api/auth/logout', { method: 'POST', credentials: 'same-origin' });
    } finally {
      setAccessToken(null);
      setUser(null);
    }
  };

  // Initial session recovery
  useEffect(() => {
    refreshToken().finally(() => setLoading(false));
  }, []);

  return (
    <AuthContext.Provider value={{ accessToken, user, loading, login, logout, refreshToken }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be used within an AuthProvider');
  return ctx;
}
`;
  }

  static _generateLoginForm(plan) {
    return `import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';

export function LoginForm({ onSuccess }) {
  const { login } = useAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      await login(email, password);
      if (onSuccess) onSuccess();
    } catch (err) {
      setError(err.message || 'Invalid credentials');
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="auth-form" aria-label="Sign in form">
      <h2>Sign In</h2>
      {error && <div role="alert" className="error-banner">{error}</div>}
      <div className="form-group">
        <label htmlFor="login-email">Email</label>
        <input
          id="login-email"
          type="email"
          required
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          autoComplete="email"
        />
      </div>
      <div className="form-group">
        <label htmlFor="login-password">Password</label>
        <input
          id="login-password"
          type="password"
          required
          maxLength={72}
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          autoComplete="current-password"
        />
      </div>
      <button type="submit" disabled={loading} className="btn-primary">
        {loading ? 'Signing in...' : 'Sign In'}
      </button>
    </form>
  );
}
`;
  }

  static _generateRegisterForm(plan) {
    return `import React, { useState } from 'react';

export function RegisterForm({ onSuccess }) {
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    if (password.length < 8) {
      setError('Password must be at least 8 characters long');
      return;
    }
    setLoading(true);
    try {
      const res = await fetch('/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password, name })
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({ error: 'Registration failed' }));
        throw new Error(data.error || 'Registration failed');
      }
      if (onSuccess) onSuccess();
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="auth-form" aria-label="Registration form">
      <h2>Create an Account</h2>
      {error && <div role="alert" className="error-banner">{error}</div>}
      <div className="form-group">
        <label htmlFor="reg-name">Full Name</label>
        <input
          id="reg-name"
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          autoComplete="name"
        />
      </div>
      <div className="form-group">
        <label htmlFor="reg-email">Email</label>
        <input
          id="reg-email"
          type="email"
          required
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          autoComplete="email"
        />
      </div>
      <div className="form-group">
        <label htmlFor="reg-password">Password (min 8 chars, max 72 bytes)</label>
        <input
          id="reg-password"
          type="password"
          required
          minLength={8}
          maxLength={72}
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          autoComplete="new-password"
        />
      </div>
      <button type="submit" disabled={loading} className="btn-primary">
        {loading ? 'Registering...' : 'Register'}
      </button>
    </form>
  );
}
`;
  }

  static _generateProtectedRoute(plan) {
    return `import React from 'react';
import { useAuth } from '../context/AuthContext';

export function ProtectedRoute({ children, requiredRole = 'user' }) {
  const { user, loading } = useAuth();

  if (loading) {
    return <div className="loading-state">Verifying authentication...</div>;
  }

  if (!user) {
    return <div className="unauthorized">Please log in to view this page.</div>;
  }

  const levels = { admin: 100, user: 10, guest: 1 };
  const userLevel = levels[user.role] || 0;
  const reqLevel = levels[requiredRole] || 0;

  if (userLevel < reqLevel) {
    return <div className="forbidden">Access Denied: Insufficient permissions.</div>;
  }

  return children;
}
`;
  }

  static _generateAuthTestSuite(plan) {
    return `'use strict';
const test = require('node:test');
const assert = require('node:assert');
const { hashPassword, verifyPassword, signJwt, verifyJwt } = require('../utils/auth');

test('Automated Security & Auth Suite', async (t) => {
  await t.test('Password hashing and verification', () => {
    const hash = hashPassword('SecurePass123');
    assert.strictEqual(verifyPassword('SecurePass123', hash), true);
    assert.strictEqual(verifyPassword('WrongPass', hash), false);
  });

  await t.test('Password length bounds (<= 72 bytes)', () => {
    const tooLong = 'A'.repeat(73);
    assert.throws(() => hashPassword(tooLong), /72 bytes/);
  });

  await t.test('JWT signing and claims verification', () => {
    const token = signJwt({ sub: 'usr_123', role: 'admin' });
    const verified = verifyJwt(token);
    assert.strictEqual(verified.valid, true);
    assert.strictEqual(verified.payload.sub, 'usr_123');
    assert.strictEqual(verified.payload.role, 'admin');
  });

  await t.test('JWT rejection on algorithm none', () => {
    const badToken = 'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ1c3JfMTIzIn0.';
    const verified = verifyJwt(badToken);
    assert.strictEqual(verified.valid, false);
  });
});
`;
  }
}

module.exports = {
  AuthSynthesizer
};
