/**
 * AppIcon — AI-Dost ka single standard icon component (Font Awesome Free).
 *
 * Standard (`.font-awesome.md` + AGENTS.md): poori site + copilot-generated
 * projects me icons sirf Font Awesome se aate hain — lucide/emoji "AI-generated"
 * look dete hain, isliye naye code me `lucide-react` import NA karein.
 *
 * Usage: <AppIcon name="search" size={15} className="text-accent" />
 *  - `name`: neeche APP_ICONS map ki key (unknown → `circle` fallback, kabhi blank nahi)
 *  - `size`: pixel font-size (FA svg 1em scale karta hai)
 *  - `loader` naam auto-spin karta hai (spin prop se override)
 */
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faPlus,
  faMagnifyingGlass,
  faClockRotateLeft,
  faGear,
  faGears,
  faMoon,
  faSun,
  faMessage,
  faPencil,
  faTrash,
  faTrashCan,
  faShareNodes,
  faCheck,
  faXmark,
  faAnglesLeft,
  faAnglesRight,
  faTerminal,
  faDroplet,
  faPuzzlePiece,
  faBuilding,
  faCode,
  faRobot,
  faFolderOpen,
  faFolderTree,
  faFolderPlus,
  faWandMagicSparkles,
  faPaperPlane,
  faPlay,
  faCircleNotch,
  faEye,
  faEyeSlash,
  faDownload,
  faSquare,
  faRotateLeft,
  faArrowsRotate,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faDatabase,
  faMobile,
  faTablet,
  faDesktop,
  faCrosshairs,
  faMicrophone,
  faMicrophoneSlash,
  faTableCells,
  faTableCellsLarge,
  faTableColumns,
  faBolt,
  faBug,
  faUpRightFromSquare,
  faCopy,
  faArrowRight,
  faArrowUp,
  faShieldHalved,
  faCartShopping,
  faChartColumn,
  faChartPie,
  faFire,
  faBrain,
  faDiagramProject,
  faBox,
  faKey,
  faTriangleExclamation,
  faCircleExclamation,
  faCircleCheck,
  faCirclePlus,
  faCircleXmark,
  faCircle,
  faVolumeHigh,
  faVolumeXmark,
  faVolumeLow,
  faWaveSquare,
  faWrench,
  faFileLines,
  faBell,
  faBars,
  faWifi,
  faLock,
  faUser,
  faUsers,
  faEnvelope,
  faStar,
  faHeart,
  faFilter,
  faWallet,
  faCoins,
  faTicket,
  faFilm,
  faCalendar,
  faHospital,
  faLayerGroup,
  faArrowTrendUp,
  faArrowTrendDown,
  faArrowRightArrowLeft,
  faCodeBranch,
  faHashtag,
  faMinus,
  faDollarSign,
  faThumbsUp,
  faThumbsDown,
  faGlobe,
  faClipboardList,
  faPaperclip,
  faImage,
  faEraser,
  faFloppyDisk,
  faListCheck,
  faBagShopping,
  faLocationDot,
  faCodeCompare,
  faFileCirclePlus,
  faArrowTurnDown,
  faArrowDownAZ,
} from '@fortawesome/free-solid-svg-icons';
import { faGithub, faGoogle, faXTwitter } from '@fortawesome/free-brands-svg-icons';

export const APP_ICONS = {
  plus: faPlus,
  search: faMagnifyingGlass,
  history: faClockRotateLeft,
  clock: faClockRotateLeft,
  settings: faGear,
  gears: faGears,
  moon: faMoon,
  sun: faSun,
  message: faMessage,
  pencil: faPencil,
  trash: faTrash,
  trashCan: faTrashCan,
  share: faShareNodes,
  check: faCheck,
  checkCircle: faCircleCheck,
  close: faXmark,
  collapse: faAnglesLeft,
  expand: faAnglesRight,
  terminal: faTerminal,
  droplets: faDroplet,
  puzzle: faPuzzlePiece,
  building: faBuilding,
  code: faCode,
  bot: faRobot,
  folderOpen: faFolderOpen,
  folderTree: faFolderTree,
  folderPlus: faFolderPlus,
  sparkles: faWandMagicSparkles,
  send: faPaperPlane,
  play: faPlay,
  loader: faCircleNotch,
  eye: faEye,
  eyeOff: faEyeSlash,
  download: faDownload,
  square: faSquare,
  rotate: faRotateLeft,
  refresh: faArrowsRotate,
  chevronRight: faChevronRight,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  chevronLeft: faChevronLeft,
  database: faDatabase,
  mobile: faMobile,
  tablet: faTablet,
  desktop: faDesktop,
  crosshair: faCrosshairs,
  mic: faMicrophone,
  micOff: faMicrophoneSlash,
  grid: faTableCells,
  layout: faTableCellsLarge,
  columns: faTableColumns,
  kanban: faTableColumns,
  zap: faBolt,
  bug: faBug,
  external: faUpRightFromSquare,
  copy: faCopy,
  arrowRight: faArrowRight,
  arrowUp: faArrowUp,
  shield: faShieldHalved,
  cart: faCartShopping,
  chart: faChartColumn,
  pie: faChartPie,
  flame: faFire,
  brain: faBrain,
  workflow: faDiagramProject,
  package: faBox,
  key: faKey,
  alert: faTriangleExclamation,
  alertCircle: faCircleExclamation,
  plusCircle: faCirclePlus,
  errorCircle: faCircleXmark,
  circle: faCircle,
  volume: faVolumeHigh,
  volumeOff: faVolumeXmark,
  volumeLow: faVolumeLow,
  waveform: faWaveSquare,
  wrench: faWrench,
  file: faFileLines,
  fileDiff: faFileLines,
  bell: faBell,
  menu: faBars,
  wifi: faWifi,
  lock: faLock,
  user: faUser,
  users: faUsers,
  mail: faEnvelope,
  star: faStar,
  heart: faHeart,
  filter: faFilter,
  wallet: faWallet,
  coins: faCoins,
  ticket: faTicket,
  film: faFilm,
  calendar: faCalendar,
  hospital: faHospital,
  layers: faLayerGroup,
  trendUp: faArrowTrendUp,
  trendDown: faArrowTrendDown,
  swap: faArrowRightArrowLeft,
  branch: faCodeBranch,
  hash: faHashtag,
  minus: faMinus,
  dollar: faDollarSign,
  thumbsUp: faThumbsUp,
  thumbsDown: faThumbsDown,
  globe: faGlobe,
  clipboard: faClipboardList,
  paperclip: faPaperclip,
  image: faImage,
  eraser: faEraser,
  save: faFloppyDisk,
  list: faListCheck,
  bag: faBagShopping,
  pin: faLocationDot,
  compare: faCodeCompare,
  filePlus: faFileCirclePlus,
  turnDown: faArrowTurnDown,
  caseSensitive: faArrowDownAZ,
  github: faGithub,
  google: faGoogle,
  xBrand: faXTwitter,
};

export default function AppIcon({ name = 'circle', size = 16, className = '', style, spin, ...rest }) {
  const icon = APP_ICONS[name] || APP_ICONS.circle;
  const autoSpin = spin ?? name === 'loader';

  // FA 7 treats icons as decorative and no longer renders a <title> child, so a
  // caller's `title` is honoured as the accessible label instead (FA's own
  // recommendation: use aria-label). Everything else is allow-listed before it
  // can reach <svg> — callers routinely spread parent props onto AppIcon and
  // React warns "does not recognize the X prop on a DOM element".
  const { title, ...raw } = rest;
  const safeRest = {};
  for (const [k, v] of Object.entries(raw)) {
    if (
      k.startsWith('data-') ||
      k.startsWith('aria-') ||
      k === 'role' ||
      k === 'tabIndex' ||
      /^on[A-Z]/.test(k) // onClick, onMouseEnter, ...
    ) {
      safeRest[k] = v;
    }
  }
  if (title && !safeRest['aria-label']) safeRest['aria-label'] = String(title);

  return (
    <FontAwesomeIcon
      icon={icon}
      spin={autoSpin}
      className={className}
      style={{ fontSize: size, ...style }}
      data-testid={`app-icon-${name}`}
      {...safeRest}
    />
  );
}
