import React from 'react';
import Link from 'next/link';
import { PublicLayout } from '../components/public/PublicLayout';
import { RevealOnScroll } from '../components/ui/RevealOnScroll';
import {
  ShieldCheck, Lock, Eye, AlertTriangle, CheckCircle2,
  FileCode, Terminal, Database, ArrowRight, ExternalLink
} from 'lucide-react';

const SECURITY_CONTROLS = [
  {
    title: 'Local-First Workstation Storage',
    category: 'Data Residency',
    desc: 'All conversation histories, generated project files, SQLite database records, and workspace configurations reside exclusively on your local machine. No telemetry or prompt logs are sent to AI-Dost cloud servers.',
    verified: 'backend/server.js, backend/data/aidost.db',
  },
  {
    title: 'Path Traversal & Perimeter Defense',
    category: 'Filesystem Protection',
    desc: 'All file read, write, and edit operations strictly validate requested paths against normalized workspace directories. Null byte injections (\\0), UNC paths, and directory traversal attempts (../) are actively blocked.',
    verified: 'backend/sandbox/sandboxManager.js, productionReadiness.test.js',
  },
  {
    title: 'Role-Based Capability Matrix',
    category: 'Agent Governance',
    desc: 'Sub-agent identities operate under non-escalatable capability policies: Supervisors only plan; Researchers only read; Coders write within project scope; Verifiers only test. No agent can expand its own permission boundaries.',
    verified: 'docs/AUTONOMOUS_EXECUTION_CONTRACT.md, capabilityPolicy.js',
  },
  {
    title: 'Human Consent for Destructive Actions',
    category: 'Authorization Gate',
    desc: 'Operations that result in irreversible state changes (deleting projects, clearing conversation history, wiping API keys) cannot be run autonomously and require manual confirmation via accessible modal dialogs.',
    verified: 'frontend/components/ui/Modal.jsx, ProjectsView.jsx, HistoryView.jsx',
  },
  {
    title: 'Client-Side & Local Key Isolation',
    category: 'Credential Safety',
    desc: 'Third-party API keys (Gemini, Groq, Tavily) are stored either in local environment files (.env) or browser localStorage. Keys are transmitted only to the designated model provider endpoints and never logged.',
    verified: 'backend/services/geminiService.js, groqService.js',
  },
  {
    title: 'Circuit Breaker & Rate Limiting',
    category: 'Resilience & DoS Defense',
    desc: 'All outbound provider API requests pass through an active CircuitBreaker and RateLimiter to prevent infinite request loops, rate-limit bans, and provider endpoint exhaustion during complex autonomous tasks.',
    verified: 'backend/services/apiClient.js, unit.test.js',
  },
  {
    title: 'Rigorous Content Sanitization',
    category: 'XSS Prevention',
    desc: 'All markdown responses and code snippets generated by AI models are parsed via marked and sanitized with DOMPurify prior to DOM insertion, preventing malicious script injections and cross-site scripting vulnerabilities.',
    verified: 'frontend/components/views/ChatView.jsx, CopilotIDE.jsx',
  },
];

export default function SecurityPage() {
  const handleCardMouseMove = (e) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;
    e.currentTarget.style.setProperty('--mouse-x', `${x}px`);
    e.currentTarget.style.setProperty('--mouse-y', `${y}px`);
  };

  return (
    <PublicLayout
      title="Security & Governance — AI-Dost Autonomous AI Workspace"
      description="Grounded technical security architecture: local data residency, path traversal defense, role-based capability boundaries, and transparent safety disclosures."
    >
      {/* ─── Header ─── */}
      <section className="relative pt-20 pb-16 md:pt-28 md:pb-20 border-b border-border bg-canvas-subtle overflow-hidden">
        {/* Google Gemini Dual Ambient Celestial Orbs */}
        <div className="absolute -top-24 left-1/4 w-[500px] h-[300px] bg-gradient-to-tr from-[#4285f4]/20 via-[#9b72cb]/18 to-transparent blur-[120px] pointer-events-none rounded-full" />
        <div className="absolute top-10 right-1/4 w-[450px] h-[300px] bg-gradient-to-bl from-[#d96570]/15 via-[#1ba1e2]/15 to-transparent blur-[120px] pointer-events-none rounded-full" />

        <RevealOnScroll direction="up" className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-4 relative z-10">
          <div className="gemini-shimmer-badge text-[11px] font-mono text-[#4893fc]">
            <ShieldCheck className="w-3.5 h-3.5 gemini-sparkle-icon" />
            <span>Security Architecture</span>
          </div>
          <h1 className="text-3xl sm:text-5xl font-bold font-display tracking-tight text-paper-100">
            Defensive <span className="gemini-gradient-text">Local Autonomy</span>
          </h1>
          <p className="text-sm sm:text-base text-ink-muted max-w-2xl mx-auto leading-relaxed">
            Autonomous software creation requires ironclad operational boundaries. We build security through verifiable local containment, mathematical role policies, and absolute transparency.
          </p>
        </RevealOnScroll>
      </section>

      {/* ─── Grounded Controls ─── */}
      <section className="py-16 md:py-24 border-b border-border">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
          <RevealOnScroll direction="up" className="space-y-2 text-center sm:text-left">
            <h2 className="text-xs font-mono uppercase tracking-[0.15em] text-[#4893fc] font-semibold">
              Verified Controls
            </h2>
            <p className="text-2xl sm:text-3xl font-bold font-display text-paper-100">
              Concrete Architectural Safeguards
            </p>
            <p className="text-xs sm:text-sm text-ink-muted max-w-xl">
              Every control below is implemented in the AI-Dost codebase and verified by automated regression test suites.
            </p>
          </RevealOnScroll>

          <div className="space-y-4">
            {SECURITY_CONTROLS.map((ctrl, i) => (
              <RevealOnScroll
                key={i}
                delay={i * 60}
                direction="up"
                onMouseMove={handleCardMouseMove}
                className="gemini-glow-card p-6 border border-white/10 space-y-2.5"
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div className="flex items-center gap-2.5">
                    <ShieldCheck className="w-4 h-4 text-[#4893fc] shrink-0" />
                    <h3 className="text-sm font-semibold font-display text-paper-100">{ctrl.title}</h3>
                  </div>
                  <span className="text-[10px] font-mono px-3 py-1 rounded-full bg-white/5 border border-white/10 text-[#9b72cb] shrink-0 self-start sm:self-auto">
                    {ctrl.category}
                  </span>
                </div>
                <p className="text-xs text-paper-200 leading-relaxed font-sans">
                  {ctrl.desc}
                </p>
                <div className="text-[10px] font-mono text-ink-muted pt-1 border-t border-border-subtle flex items-center gap-1.5">
                  <span className="text-[#4893fc] font-semibold">Code Evidence:</span>
                  <span>{ctrl.verified}</span>
                </div>
              </RevealOnScroll>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Transparent Boundaries (Honest Disclosures) ─── */}
      <section className="py-16 md:py-24 bg-canvas-subtle border-b border-border">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
          <div className="space-y-2 text-center sm:text-left">
            <h2 className="text-xs font-mono uppercase tracking-[0.15em] text-[#4893fc] font-semibold">
              Transparent Disclosures
            </h2>
            <p className="text-2xl sm:text-3xl font-bold font-display text-paper-100">
              Architecture Boundaries & Truth in Security
            </p>
            <p className="text-xs sm:text-sm text-ink-muted max-w-xl">
              We do not fabricate certifications or inflate guarantees. Here are the genuine parameters of the current system:
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="gemini-glow-card p-6 border border-white/10 space-y-3">
              <div className="flex items-center gap-2 text-paper-100 font-semibold text-sm">
                <AlertTriangle className="w-4 h-4 text-signal-warning" />
                <span>No Fabricated Compliance Badges</span>
              </div>
              <p className="text-xs text-ink-muted leading-relaxed font-sans">
                AI-Dost does NOT claim formal SOC 2 Type II, HIPAA, or ISO 27001 certifications. Our security model is based on open-source auditability, local data residency, and deterministic code containment rather than third-party compliance marketing badges.
              </p>
            </div>

            <div className="gemini-glow-card p-6 border border-white/10 space-y-3">
              <div className="flex items-center gap-2 text-paper-100 font-semibold text-sm">
                <Lock className="w-4 h-4 text-signal-warning" />
                <span>Third-Party Cloud Inference Boundaries</span>
              </div>
              <p className="text-xs text-ink-muted leading-relaxed font-sans">
                When using cloud providers (Google Gemini, Groq, OpenRouter), your prompt data is governed by those respective platforms&apos; privacy terms. For 100% offline air-gapped security, configure the local Ollama provider where zero network requests leave your computer.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Responsible Disclosure ─── */}
      <section className="py-16 text-center space-y-4">
        <h3 className="text-xl sm:text-2xl font-bold font-display text-paper-100">
          Responsible Vulnerability Disclosure
        </h3>
        <p className="text-xs sm:text-sm text-ink-muted max-w-xl mx-auto">
          If you discover a security vulnerability or perimeter bypass in AI-Dost, please open a confidential security advisory on our GitHub repository or contact the maintainers.
        </p>
        <div className="pt-2">
          <Link
            href="/support"
            className="gemini-btn-primary inline-flex items-center gap-2 px-6 py-2.5 rounded-full text-xs font-semibold transition-fast shadow-md"
          >
            <span>Security Reporting Guidelines</span>
            <ExternalLink className="w-3.5 h-3.5" />
          </Link>
        </div>
      </section>
    </PublicLayout>
  );
}
