import React, { useState, useEffect, useCallback } from 'react';
import {
  FileText, Download, Eye, RefreshCw, FileSpreadsheet,
  Presentation, FileCode, CheckCircle2, Trash2, ExternalLink
} from 'lucide-react';
import { Button } from '../ui/Button';
import { Badge } from '../ui/Badge';
import { EmptyState } from '../ui/EmptyState';
import { SkeletonTableRow } from '../ui/Skeleton';

export default function ArtifactsView({ onToast }) {
  const [artifacts, setArtifacts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [selectedArtifact, setSelectedArtifact] = useState(null);

  const load = useCallback(() => {
    setLoading(true);
    try {
      // Collect generated artifact downloads from local state/storage
      const stored = localStorage.getItem('ai_dost_generated_artifacts');
      const list = stored ? JSON.parse(stored) : [];
      setArtifacts(Array.isArray(list) ? list : []);
    } catch (_) {
      setArtifacts([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const getIcon = (type) => {
    const t = (type || '').toLowerCase();
    if (t.includes('pdf') || t.includes('doc')) return FileText;
    if (t.includes('csv') || t.includes('xlsx') || t.includes('sheet')) return FileSpreadsheet;
    if (t.includes('ppt') || t.includes('slide')) return Presentation;
    return FileCode;
  };

  const removeArtifact = (id, e) => {
    e.stopPropagation();
    const updated = artifacts.filter((a) => a.id !== id);
    setArtifacts(updated);
    localStorage.setItem('ai_dost_generated_artifacts', JSON.stringify(updated));
    if (onToast) onToast('Artifact removed from shelf', 'success');
  };

  return (
    <div className="h-full overflow-y-auto px-4 sm:px-8 py-6 bg-canvas-base select-none">
      <div className="max-w-5xl mx-auto space-y-6">
        {/* Header Strip */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-border">
          <div>
            <h1 className="text-lg font-semibold text-paper-100 font-display">
              Document & Artifact Shelf
            </h1>
            <p className="text-xs text-ink-muted mt-0.5">
              Verified documents, data sheets, presentations, and code artifacts generated by AI-Dost.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <Button
              variant="secondary"
              size="sm"
              icon={RefreshCw}
              onClick={load}
              disabled={loading}
            >
              Refresh
            </Button>
          </div>
        </div>

        {/* Editorial Table / List */}
        {loading ? (
          <div className="rounded-sm border border-border bg-canvas-surface overflow-hidden divide-y divide-border-subtle shadow-sm">
            <SkeletonTableRow />
            <SkeletonTableRow />
            <SkeletonTableRow />
          </div>
        ) : artifacts.length === 0 ? (
          <EmptyState
            icon={FileText}
            title="No generated artifacts yet"
            description="Generate a PDF report, Excel sheet, presentation, or DOCX document in Chat to see it archived here."
          />
        ) : (
          <div className="rounded-sm border border-border bg-canvas-surface overflow-hidden shadow-sm">
            {/* Table Header */}
            <div className="grid grid-cols-12 px-4 py-2.5 bg-canvas-subtle border-b border-border text-[11px] font-mono uppercase tracking-wider text-ink-muted">
              <div className="col-span-5 sm:col-span-4">Artifact Name</div>
              <div className="col-span-3 sm:col-span-3">Type / Format</div>
              <div className="col-span-2 sm:col-span-3 hidden sm:block">Created</div>
              <div className="col-span-4 sm:col-span-2 text-right">Actions</div>
            </div>

            {/* Table Rows */}
            <div className="divide-y divide-border-subtle font-sans text-xs">
              {artifacts.map((art) => {
                const Icon = getIcon(art.type);
                return (
                  <div
                    key={art.id || art.url}
                    className="grid grid-cols-12 items-center px-4 py-3 hover:bg-canvas-elevated transition-fast cursor-pointer group"
                    onClick={() => setSelectedArtifact(art)}
                  >
                    <div className="col-span-5 sm:col-span-4 flex items-center gap-2.5 min-w-0 pr-2">
                      <Icon className="w-4 h-4 text-accent-primary flex-shrink-0" />
                      <div className="min-w-0">
                        <div className="font-medium text-paper-100 truncate group-hover:text-accent-primary transition-fast">
                          {art.title || art.name || 'Generated Document'}
                        </div>
                        <div className="font-mono text-[10px] text-ink-muted truncate sm:hidden">
                          {art.type || 'DOCUMENT'}
                        </div>
                      </div>
                    </div>

                    <div className="col-span-3 sm:col-span-3">
                      <span className="font-mono text-[10px] uppercase px-1.5 py-0.5 rounded-xs bg-canvas-base border border-border text-paper-200">
                        {art.type || 'FILE'}
                      </span>
                    </div>

                    <div className="col-span-2 sm:col-span-3 text-ink-muted font-mono text-[11px] hidden sm:block">
                      {art.created_at ? new Date(art.created_at).toLocaleDateString() : 'Recent'}
                    </div>

                    <div className="col-span-4 sm:col-span-2 flex items-center justify-end gap-1.5">
                      {art.url && (
                        <a
                          href={art.url}
                          download
                          onClick={(e) => e.stopPropagation()}
                          className="p-1 rounded-xs text-ink-muted hover:text-paper-100 hover:bg-canvas-base transition-fast cursor-pointer"
                          title="Download File"
                        >
                          <Download className="w-3.5 h-3.5" />
                        </a>
                      )}
                      <button
                        type="button"
                        onClick={(e) => removeArtifact(art.id, e)}
                        className="p-1 rounded-xs text-ink-muted hover:text-signal-error hover:bg-canvas-base transition-fast cursor-pointer"
                        title="Delete from Shelf"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* Artifact Detail Modal / Drawer */}
      {selectedArtifact && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-xs p-4">
          <div className="w-full max-w-md rounded-sm bg-canvas-surface border border-border p-5 shadow-modal space-y-4">
            <div className="flex items-center justify-between border-b border-border-subtle pb-2">
              <h3 className="text-sm font-semibold text-paper-100 font-display">
                Artifact Details
              </h3>
              <button
                type="button"
                onClick={() => setSelectedArtifact(null)}
                className="p-1 text-ink-muted hover:text-paper-100 cursor-pointer"
              >
                ✕
              </button>
            </div>

            <div className="space-y-2 text-xs font-mono">
              <div className="flex justify-between py-1 border-b border-border-subtle">
                <span className="text-ink-muted">Title:</span>
                <span className="text-paper-100">{selectedArtifact.title || selectedArtifact.name}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-border-subtle">
                <span className="text-ink-muted">Format:</span>
                <span className="text-paper-100 uppercase">{selectedArtifact.type}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-border-subtle">
                <span className="text-ink-muted">Path:</span>
                <span className="text-paper-200 truncate max-w-[200px]">{selectedArtifact.url || 'local-shelf'}</span>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <Button variant="ghost" size="sm" onClick={() => setSelectedArtifact(null)}>
                Close
              </Button>
              {selectedArtifact.url && (
                <a href={selectedArtifact.url} download>
                  <Button variant="primary" size="sm" icon={Download}>
                    Download
                  </Button>
                </a>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
