/**
 * PlaywrightAdapter - Adapter for Playwright end-to-end and browser testing
 *
 * Produces standard Playwright test specs using @playwright/test.
 */

class PlaywrightAdapter {
  constructor(options = {}) {
    this.name = 'playwright';
    this.framework = 'playwright';
    this.options = options;
  }

  /**
   * Builds execution command line and args for running tests with Playwright
   * @param {string[]} testFilePaths
   * @param {object} runOptions
   * @returns {{ command: string, args: string[] }}
   */
  buildRunCommand(testFilePaths = [], runOptions = {}) {
    const args = ['playwright', 'test'];
    if (runOptions.timeoutMs) {
      args.push(`--timeout=${runOptions.timeoutMs}`);
    }
    if (runOptions.headed) {
      args.push('--headed');
    }
    if (testFilePaths.length > 0) {
      args.push(...testFilePaths);
    }
    return {
      command: 'npx',
      args
    };
  }

  /**
   * Synthesizes Playwright browser test spec
   * @param {object} spec
   * @returns {string}
   */
  generateTestFile(spec = {}) {
    const { targetName = 'Application E2E', testCases = [], baseUrl = 'http://localhost:3000' } = spec;

    const lines = [
      '// Generated by AI Dost 2.0 Automated Test Case Generation (Playwright)',
      'const { test, expect } = require(\'@playwright/test\');',
      ''
    ];

    lines.push(`test.describe('${this._escapeString(targetName)}', () => {`);
    lines.push(`  const BASE_URL = process.env.BASE_URL || '${baseUrl}';`);
    lines.push('');

    if (!testCases || testCases.length === 0) {
      lines.push('  test(\'should navigate to home page and verify root element\', async ({ page }) => {');
      lines.push('    await page.goto(BASE_URL);');
      lines.push('    await expect(page).toHaveTitle(/.+/);');
      lines.push('  });');
    } else {
      for (const tc of testCases) {
        lines.push(`  test('${this._escapeString(tc.description || 'should perform browser flow')}', async ({ page }) => {`);
        if (tc.body) {
          const indentedBody = tc.body
            .split('\n')
            .map(line => `    ${line}`)
            .join('\n');
          lines.push(indentedBody);
        } else {
          lines.push('    await page.goto(BASE_URL);');
          lines.push('    expect(page.url()).toBeTruthy();');
        }
        lines.push('  });');
        lines.push('');
      }
    }

    lines.push('});');
    lines.push('');

    return lines.join('\n');
  }

  _escapeString(str) {
    return String(str).replace(/'/g, "\\'");
  }
}

PlaywrightAdapter.PlaywrightAdapter = PlaywrightAdapter;
module.exports = PlaywrightAdapter;
