/**
 * AI-Dost Full-Stack Archetype: Modern Cyberpunk Neon Calculator
 * Zero-placeholder, 100% production-ready React + Express architecture.
 */

function getCalculatorBlueprint(name, title, prompt) {
  const safeTitle = title || 'Cyberpunk Neon Calculator';

  const packageJson = JSON.stringify({
    name: name || 'neon-calculator',
    version: '1.0.0',
    private: true,
    type: 'module',
    scripts: { dev: 'vite', build: 'vite build', server: 'node server.js', start: 'vite' },
    dependencies: {
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      'lucide-react': '^0.344.0',
      express: '^4.18.2',
      cors: '^2.8.5'
    },
    devDependencies: { '@vitejs/plugin-react': '^4.2.1', vite: '^5.1.4' }
  }, null, 2);

  const viteConfig = [
    "import { defineConfig } from 'vite';",
    "import react from '@vitejs/plugin-react';",
    "",
    "export default defineConfig({",
    "  plugins: [react()],",
    "  server: { port: 5173, host: '0.0.0.0', proxy: { '/api': 'http://localhost:5000' } }",
    "});"
  ].join('\n');

  const indexHtml = [
    '<!DOCTYPE html>',
    '<html lang="en" class="dark">',
    '  <head>',
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    '    <title>' + safeTitle + ' | Cyberpunk Neon Calculator</title>',
    '    <script src="https://cdn.tailwindcss.com"></script>',
    '    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;600;700&display=swap" rel="stylesheet">',
    '    <style>',
    "      body { font-family: 'Plus Jakarta Sans', sans-serif; background: #07090e; color: #f8fafc; margin: 0; }",
    "      .font-mono { font-family: 'JetBrains Mono', monospace; }",
    '    </style>',
    '  </head>',
    '  <body class="bg-[#07090e] text-zinc-100 min-h-screen antialiased selection:bg-cyan-500 selection:text-black">',
    '    <div id="root"></div>',
    '    <script type="module" src="/src/main.jsx"></script>',
    '  </body>',
    '</html>'
  ].join('\n');

  const serverJs = [
    "const express = require('express');",
    "const cors = require('cors');",
    "",
    "const app = express();",
    "const PORT = process.env.PORT || 5000;",
    "",
    "app.use(cors());",
    "app.use(express.json());",
    "",
    "let history = [",
    "  { id: '1', expression: '250 × 12', result: '3000', timestamp: '10 mins ago' },",
    "  { id: '2', expression: '1500 + 18%', result: '1770', timestamp: '25 mins ago' },",
    "  { id: '3', expression: '√(144) + 5²', result: '37', timestamp: '1 hour ago' }",
    "];",
    "",
    "app.get('/api/history', (req, res) => {",
    "  res.json({ success: true, history });",
    "});",
    "",
    "app.post('/api/history', (req, res) => {",
    "  const { expression, result } = req.body;",
    "  if (!expression || result === undefined) {",
    "    return res.status(400).json({ success: false, error: 'Expression and result required' });",
    "  }",
    "  const item = {",
    "    id: String(Date.now()),",
    "    expression,",
    "    result: String(result),",
    "    timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })",
    "  };",
    "  history.unshift(item);",
    "  if (history.length > 50) history.pop();",
    "  res.json({ success: true, item, history });",
    "});",
    "",
    "app.delete('/api/history', (req, res) => {",
    "  history = [];",
    "  res.json({ success: true, message: 'History cleared', history: [] });",
    "});",
    "",
    "app.delete('/api/history/:id', (req, res) => {",
    "  history = history.filter(h => h.id !== req.params.id);",
    "  res.json({ success: true, history });",
    "});",
    "",
    "app.get('/api/health', (req, res) => {",
    "  res.json({ status: 'healthy', service: 'Calculator History API', timestamp: new Date().toISOString() });",
    "});",
    "",
    "if (process.env.NODE_ENV !== 'test') {",
    "  app.listen(PORT, () => console.log('Calculator API running on port ' + PORT));",
    "}",
    "",
    "module.exports = app;"
  ].join('\n');

  const apiJs = [
    "export const API = {",
    "  async getHistory() {",
    "    try {",
    "      const res = await fetch('/api/history');",
    "      if (!res.ok) throw new Error('Failed to fetch history');",
    "      const data = await res.json();",
    "      return data.history || [];",
    "    } catch (_) {",
    "      try { return JSON.parse(localStorage.getItem('calc_history') || '[]'); } catch(e) { return []; }",
    "    }",
    "  },",
    "",
    "  async saveCalculation(expression, result) {",
    "    const item = { id: String(Date.now()), expression, result: String(result), timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) };",
    "    try {",
    "      const res = await fetch('/api/history', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ expression, result }) });",
    "      if (res.ok) { const data = await res.json(); return data.item || item; }",
    "    } catch (_) {}",
    "    try {",
    "      const cur = JSON.parse(localStorage.getItem('calc_history') || '[]');",
    "      cur.unshift(item);",
    "      localStorage.setItem('calc_history', JSON.stringify(cur.slice(0, 50)));",
    "    } catch (_) {}",
    "    return item;",
    "  },",
    "",
    "  async clearHistory() {",
    "    try { await fetch('/api/history', { method: 'DELETE' }); } catch (_) {}",
    "    try { localStorage.removeItem('calc_history'); } catch (_) {}",
    "    return true;",
    "  }",
    "};"
  ].join('\n');

  const indexCss = [
    "@tailwind base;",
    "@tailwind components;",
    "@tailwind utilities;",
    "",
    "@layer utilities {",
    "  .glow-cyan { box-shadow: 0 0 25px rgba(6, 182, 212, 0.45); }",
    "  .glow-indigo { box-shadow: 0 0 25px rgba(99, 102, 241, 0.45); }",
    "  .glow-amber { box-shadow: 0 0 25px rgba(245, 158, 11, 0.45); }",
    "}"
  ].join('\n');

  const mainJsx = [
    "import React from 'react';",
    "import ReactDOM from 'react-dom/client';",
    "import App from './App';",
    "import './index.css';",
    "",
    "ReactDOM.createRoot(document.getElementById('root')).render(",
    "  <React.StrictMode>",
    "    <App />",
    "  </React.StrictMode>",
    ");"
  ].join('\n');

  const appJsx = [
    "import React, { useState, useEffect } from 'react';",
    "import { History, Trash2, Sparkles, X, Check, Copy, Volume2, VolumeX } from 'lucide-react';",
    "import { API } from './services/api';",
    "",
    "export default function App() {",
    "  const [display, setDisplay] = useState('0');",
    "  const [equation, setEquation] = useState('');",
    "  const [prevValue, setPrevValue] = useState(null);",
    "  const [operator, setOperator] = useState(null);",
    "  const [waitingForOperand, setWaitingForOperand] = useState(false);",
    "  const [memory, setMemory] = useState(0);",
    "  const [history, setHistory] = useState([]);",
    "  const [historyOpen, setHistoryOpen] = useState(false);",
    "  const [soundEnabled, setSoundEnabled] = useState(true);",
    "  const [copied, setCopied] = useState(false);",
    "  const [lastCalculated, setLastCalculated] = useState(false);",
    "",
    "  useEffect(() => {",
    "    API.getHistory().then(items => { if (items && items.length > 0) setHistory(items); });",
    "  }, []);",
    "",
    "  useEffect(() => {",
    "    const handleKeyDown = (e) => {",
    "      if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;",
    "      const key = e.key;",
    "      if (/[0-9]/.test(key)) inputDigit(key);",
    "      else if (key === '.') inputDot();",
    "      else if (key === '+') performOperation('+');",
    "      else if (key === '-') performOperation('-');",
    "      else if (key === '*' || key === 'x') performOperation('×');",
    "      else if (key === '/') { e.preventDefault(); performOperation('÷'); }",
    "      else if (key === 'Enter' || key === '=') { e.preventDefault(); calculate(); }",
    "      else if (key === 'Backspace') handleBackspace();",
    "      else if (key === 'Escape' || key.toLowerCase() === 'c') clearAll();",
    "      else if (key === '%') inputPercent();",
    "    };",
    "    window.addEventListener('keydown', handleKeyDown);",
    "    return () => window.removeEventListener('keydown', handleKeyDown);",
    "  }, [display, prevValue, operator, waitingForOperand, equation]);",
    "",
    "  const playClick = (pitch = 440) => {",
    "    if (!soundEnabled || typeof window === 'undefined') return;",
    "    try {",
    "      const AudioCtx = window.AudioContext || window.webkitAudioContext;",
    "      if (!AudioCtx) return;",
    "      const ctx = new AudioCtx();",
    "      const osc = ctx.createOscillator();",
    "      const gain = ctx.createGain();",
    "      osc.type = 'sine';",
    "      osc.frequency.setValueAtTime(pitch, ctx.currentTime);",
    "      gain.gain.setValueAtTime(0.04, ctx.currentTime);",
    "      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.05);",
    "      osc.connect(gain); gain.connect(ctx.destination);",
    "      osc.start(); osc.stop(ctx.currentTime + 0.05);",
    "    } catch (_) {}",
    "  };",
    "",
    "  const inputDigit = (digit) => {",
    "    playClick(600 + parseInt(digit) * 30);",
    "    if (waitingForOperand || lastCalculated) {",
    "      setDisplay(String(digit));",
    "      setWaitingForOperand(false);",
    "      setLastCalculated(false);",
    "    } else {",
    "      setDisplay(display === '0' ? String(digit) : display + digit);",
    "    }",
    "  };",
    "",
    "  const inputDot = () => {",
    "    playClick(750);",
    "    if (waitingForOperand || lastCalculated) {",
    "      setDisplay('0.');",
    "      setWaitingForOperand(false);",
    "      setLastCalculated(false);",
    "      return;",
    "    }",
    "    if (!display.includes('.')) setDisplay(display + '.');",
    "  };",
    "",
    "  const clearAll = () => {",
    "    playClick(320);",
    "    setDisplay('0');",
    "    setEquation('');",
    "    setPrevValue(null);",
    "    setOperator(null);",
    "    setWaitingForOperand(false);",
    "    setLastCalculated(false);",
    "  };",
    "",
    "  const handleBackspace = () => {",
    "    playClick(400);",
    "    if (waitingForOperand || lastCalculated) return;",
    "    if (display.length > 1) setDisplay(display.slice(0, -1));",
    "    else setDisplay('0');",
    "  };",
    "",
    "  const toggleSign = () => {",
    "    playClick(500);",
    "    const val = parseFloat(display);",
    "    if (val !== 0) setDisplay(String(-val));",
    "  };",
    "",
    "  const inputPercent = () => {",
    "    playClick(520);",
    "    const val = parseFloat(display);",
    "    setDisplay(String(val / 100));",
    "  };",
    "",
    "  const squareRoot = () => {",
    "    playClick(540);",
    "    const val = parseFloat(display);",
    "    if (val < 0) { setDisplay('Error'); return; }",
    "    const res = Math.sqrt(val);",
    "    const formatted = parseFloat(res.toFixed(8)).toString();",
    "    setEquation('√(' + val + ') =');",
    "    setDisplay(formatted);",
    "    setLastCalculated(true);",
    "    saveToHistory('√(' + val + ')', formatted);",
    "  };",
    "",
    "  const square = () => {",
    "    playClick(560);",
    "    const val = parseFloat(display);",
    "    const formatted = parseFloat((val * val).toFixed(8)).toString();",
    "    setEquation('sqr(' + val + ') =');",
    "    setDisplay(formatted);",
    "    setLastCalculated(true);",
    "    saveToHistory('sqr(' + val + ')', formatted);",
    "  };",
    "",
    "  const reciprocal = () => {",
    "    playClick(580);",
    "    const val = parseFloat(display);",
    "    if (val === 0) { setDisplay('Cannot divide by 0'); setLastCalculated(true); return; }",
    "    const formatted = parseFloat((1 / val).toFixed(8)).toString();",
    "    setEquation('1/(' + val + ') =');",
    "    setDisplay(formatted);",
    "    setLastCalculated(true);",
    "    saveToHistory('1/(' + val + ')', formatted);",
    "  };",
    "",
    "  const memoryClear = () => { playClick(300); setMemory(0); };",
    "  const memoryRecall = () => { playClick(650); setDisplay(String(memory)); setWaitingForOperand(true); };",
    "  const memoryAdd = () => { playClick(700); setMemory(prev => prev + (parseFloat(display) || 0)); setWaitingForOperand(true); };",
    "  const memorySubtract = () => { playClick(680); setMemory(prev => prev - (parseFloat(display) || 0)); setWaitingForOperand(true); };",
    "  const memoryStore = () => { playClick(720); setMemory(parseFloat(display) || 0); setWaitingForOperand(true); };",
    "",
    "  const performOperation = (nextOperator) => {",
    "    playClick(850);",
    "    const inputValue = parseFloat(display);",
    "    if (prevValue === null) {",
    "      setPrevValue(inputValue);",
    "      setEquation(display + ' ' + nextOperator);",
    "    } else if (operator) {",
    "      if (waitingForOperand) {",
    "        setOperator(nextOperator);",
    "        setEquation(prevValue + ' ' + nextOperator);",
    "        return;",
    "      }",
    "      const result = compute(prevValue, inputValue, operator);",
    "      if (result === 'Error' || result === 'Cannot divide by 0') {",
    "        setDisplay(result); setPrevValue(null); setOperator(null);",
    "        setWaitingForOperand(false); setLastCalculated(true); return;",
    "      }",
    "      setPrevValue(result);",
    "      setDisplay(String(result));",
    "      setEquation(result + ' ' + nextOperator);",
    "    }",
    "    setWaitingForOperand(true);",
    "    setOperator(nextOperator);",
    "    setLastCalculated(false);",
    "  };",
    "",
    "  const compute = (first, second, op) => {",
    "    switch (op) {",
    "      case '+': return first + second;",
    "      case '-': return first - second;",
    "      case '×': return first * second;",
    "      case '÷': return second === 0 ? 'Cannot divide by 0' : first / second;",
    "      default: return second;",
    "    }",
    "  };",
    "",
    "  const calculate = () => {",
    "    if (operator === null || prevValue === null) return;",
    "    playClick(950);",
    "    const inputValue = parseFloat(display);",
    "    const fullExpr = prevValue + ' ' + operator + ' ' + inputValue;",
    "    const result = compute(prevValue, inputValue, operator);",
    "    if (result === 'Cannot divide by 0' || result === 'Error') {",
    "      setDisplay(result); setEquation(fullExpr + ' ='); setPrevValue(null);",
    "      setOperator(null); setLastCalculated(true); return;",
    "    }",
    "    const formatted = parseFloat(Number(result).toFixed(10)).toString();",
    "    setEquation(fullExpr + ' =');",
    "    setDisplay(formatted);",
    "    setPrevValue(null);",
    "    setOperator(null);",
    "    setWaitingForOperand(false);",
    "    setLastCalculated(true);",
    "    saveToHistory(fullExpr, formatted);",
    "  };",
    "",
    "  const saveToHistory = async (expr, res) => {",
    "    const saved = await API.saveCalculation(expr, res);",
    "    setHistory(prev => [saved, ...prev]);",
    "  };",
    "",
    "  const handleClearHistory = async () => {",
    "    await API.clearHistory();",
    "    setHistory([]);",
    "  };",
    "",
    "  const recallHistoryItem = (item) => {",
    "    setDisplay(String(item.result));",
    "    setEquation(item.expression + ' =');",
    "    setWaitingForOperand(true);",
    "    setLastCalculated(true);",
    "    setHistoryOpen(false);",
    "  };",
    "",
    "  const copyDisplay = () => {",
    "    navigator.clipboard?.writeText(display);",
    "    setCopied(true);",
    "    setTimeout(() => setCopied(false), 1500);",
    "  };",
    "",
    "  return (",
    '    <div className="min-h-screen bg-[#07090e] text-white flex flex-col items-center justify-center p-4 relative overflow-hidden select-none">',
    '      <div className="absolute top-1/4 left-1/3 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />',
    '      <div className="absolute bottom-1/4 right-1/3 translate-x-1/2 translate-y-1/2 w-96 h-96 bg-indigo-600/15 rounded-full blur-3xl pointer-events-none" />',
    "",
    '      <div className="relative w-full max-w-[420px] bg-slate-900/60 backdrop-blur-2xl border border-white/10 rounded-[2.5rem] shadow-2xl p-6 transition-all duration-300">',
    '        <div className="flex items-center justify-between pb-4 border-b border-white/5 mb-4">',
    '          <div className="flex items-center gap-2">',
    '            <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-cyan-500 to-indigo-600 flex items-center justify-center shadow-lg shadow-cyan-500/20">',
    '              <Sparkles size={16} className="text-white" />',
    '            </div>',
    '            <div>',
    '              <h1 className="text-sm font-bold tracking-tight text-white flex items-center gap-1.5">',
    '                NEON CALC',
    '                <span className="text-[10px] uppercase font-mono px-1.5 py-0.5 rounded bg-cyan-500/20 text-cyan-400 border border-cyan-500/30">v2.0</span>',
    '              </h1>',
    '              <p className="text-[10px] text-zinc-400 font-mono">Memory + History Tape</p>',
    '            </div>',
    '          </div>',
    "",
    '          <div className="flex items-center gap-2">',
    '            <button onClick={() => setSoundEnabled(!soundEnabled)} className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-zinc-400 hover:text-white transition-all cursor-pointer">',
    '              {soundEnabled ? <Volume2 size={16} className="text-cyan-400" /> : <VolumeX size={16} />}',
    '            </button>',
    '            <button onClick={() => setHistoryOpen(true)} className="relative flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/5 hover:bg-white/10 text-zinc-300 hover:text-white transition-all border border-white/5 cursor-pointer text-xs font-mono">',
    '              <History size={14} className="text-indigo-400" />',
    '              <span>Tape</span>',
    '              {history.length > 0 && <span className="px-1.5 py-0.2 rounded-full text-[9px] font-bold bg-indigo-600 text-white">{history.length}</span>}',
    '            </button>',
    '          </div>',
    '        </div>',
    "",
    '        <div className="bg-[#03060a]/80 border border-white/10 rounded-2xl p-4 mb-4 relative overflow-hidden shadow-inner group">',
    '          <div className="flex items-center justify-between text-[11px] font-mono text-zinc-400 mb-1 min-h-[16px]">',
    '            <div className="flex items-center gap-2">',
    '              {memory !== 0 && <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 animate-pulse">M = {memory}</span>}',
    '              {operator && <span className="text-amber-400 font-bold">[{operator}]</span>}',
    '            </div>',
    '            <div className="flex items-center gap-1.5">',
    '              <span className="truncate max-w-[220px] text-zinc-500">{equation || ""}</span>',
    '              <button onClick={copyDisplay} className="opacity-0 group-hover:opacity-100 transition-opacity p-1 text-zinc-400 hover:text-cyan-400 cursor-pointer">',
    '                {copied ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}',
    '              </button>',
    '            </div>',
    '          </div>',
    '          <div className="text-right overflow-x-auto scrollbar-none font-mono">',
    '            <span className={"font-bold tracking-tight text-white " + (display.length > 12 ? "text-2xl" : display.length > 8 ? "text-3xl" : "text-4xl")}>',
    '              {display}',
    '            </span>',
    '          </div>',
    '        </div>',
    "",
    '        <div className="grid grid-cols-5 gap-1.5 mb-3">',
    '          {[',
    '            { label: "MC", action: memoryClear, title: "Memory Clear" },',
    '            { label: "MR", action: memoryRecall, title: "Memory Recall" },',
    '            { label: "M+", action: memoryAdd, title: "Memory Add" },',
    '            { label: "M-", action: memorySubtract, title: "Memory Subtract" },',
    '            { label: "MS", action: memoryStore, title: "Memory Store" },',
    '          ].map((m, idx) => (',
    '            <button key={idx} onClick={m.action} className="py-1.5 rounded-lg bg-white/[0.04] hover:bg-cyan-500/20 text-cyan-400 hover:text-cyan-300 border border-white/5 hover:border-cyan-500/30 text-[11px] font-mono font-semibold transition-all active:scale-95 cursor-pointer text-center" title={m.title}>',
    '              {m.label}',
    '            </button>',
    '          ))}',
    '        </div>',
    "",
    '        <div className="grid grid-cols-4 gap-2 mb-3">',
    '          <button onClick={squareRoot} className="py-2 rounded-xl bg-white/[0.04] hover:bg-white/[0.08] text-indigo-300 font-mono text-xs font-semibold border border-white/5 transition-all active:scale-95 cursor-pointer">√x</button>',
    '          <button onClick={square} className="py-2 rounded-xl bg-white/[0.04] hover:bg-white/[0.08] text-indigo-300 font-mono text-xs font-semibold border border-white/5 transition-all active:scale-95 cursor-pointer">x²</button>',
    '          <button onClick={reciprocal} className="py-2 rounded-xl bg-white/[0.04] hover:bg-white/[0.08] text-indigo-300 font-mono text-xs font-semibold border border-white/5 transition-all active:scale-95 cursor-pointer">1/x</button>',
    '          <button onClick={inputPercent} className="py-2 rounded-xl bg-white/[0.04] hover:bg-white/[0.08] text-indigo-300 font-mono text-xs font-semibold border border-white/5 transition-all active:scale-95 cursor-pointer">%</button>',
    '        </div>',
    "",
    '        <div className="grid grid-cols-4 gap-2">',
    '          <button onClick={clearAll} className="py-3 rounded-2xl bg-rose-500/15 hover:bg-rose-500/25 text-rose-400 border border-rose-500/30 font-mono font-bold text-sm transition-all active:scale-95 cursor-pointer shadow-sm">AC</button>',
    '          <button onClick={handleBackspace} className="py-3 rounded-2xl bg-white/[0.06] hover:bg-white/[0.12] text-zinc-300 border border-white/5 font-mono font-bold text-sm transition-all active:scale-95 cursor-pointer">⌫</button>',
    '          <button onClick={toggleSign} className="py-3 rounded-2xl bg-white/[0.06] hover:bg-white/[0.12] text-zinc-300 border border-white/5 font-mono font-bold text-sm transition-all active:scale-95 cursor-pointer">±</button>',
    '          <button onClick={() => performOperation("÷")} className={"py-3 rounded-2xl font-mono font-bold text-base transition-all active:scale-95 cursor-pointer border " + (operator === "÷" ? "bg-amber-500 text-black border-amber-400 shadow-lg shadow-amber-500/30" : "bg-amber-500/15 hover:bg-amber-500/25 text-amber-400 border-amber-500/30")}>÷</button>',
    '          <button onClick={() => inputDigit("7")} className="py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer">7</button>',
    '          <button onClick={() => inputDigit("8")} className="py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer">8</button>',
    '          <button onClick={() => inputDigit("9")} className="py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer">9</button>',
    '          <button onClick={() => performOperation("×")} className={"py-3 rounded-2xl font-mono font-bold text-base transition-all active:scale-95 cursor-pointer border " + (operator === "×" ? "bg-amber-500 text-black border-amber-400 shadow-lg shadow-amber-500/30" : "bg-amber-500/15 hover:bg-amber-500/25 text-amber-400 border-amber-500/30")}>×</button>',
    '          <button onClick={() => inputDigit("4")} className="py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer">4</button>',
    '          <button onClick={() => inputDigit("5")} className="py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer">5</button>',
    '          <button onClick={() => inputDigit("6")} className="py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer">6</button>',
    '          <button onClick={() => performOperation("-")} className={"py-3 rounded-2xl font-mono font-bold text-base transition-all active:scale-95 cursor-pointer border " + (operator === "-" ? "bg-amber-500 text-black border-amber-400 shadow-lg shadow-amber-500/30" : "bg-amber-500/15 hover:bg-amber-500/25 text-amber-400 border-amber-500/30")}>-</button>',
    '          <button onClick={() => inputDigit("1")} className="py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer">1</button>',
    '          <button onClick={() => inputDigit("2")} className="py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer">2</button>',
    '          <button onClick={() => inputDigit("3")} className="py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer">3</button>',
    '          <button onClick={() => performOperation("+")} className={"py-3 rounded-2xl font-mono font-bold text-base transition-all active:scale-95 cursor-pointer border " + (operator === "+" ? "bg-amber-500 text-black border-amber-400 shadow-lg shadow-amber-500/30" : "bg-amber-500/15 hover:bg-amber-500/25 text-amber-400 border-amber-500/30")}>+</button>',
    '          <button onClick={() => inputDigit("0")} className="col-span-2 py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer text-left pl-6">0</button>',
    '          <button onClick={inputDot} className="py-3 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] text-white border border-white/5 font-mono font-bold text-base transition-all active:scale-95 cursor-pointer">.</button>',
    '          <button onClick={calculate} className="py-3 rounded-2xl bg-gradient-to-r from-cyan-500 via-indigo-600 to-purple-600 hover:from-cyan-400 hover:to-purple-500 text-white font-mono font-bold text-lg shadow-lg shadow-indigo-500/30 transition-all active:scale-95 cursor-pointer flex items-center justify-center">=</button>',
    '        </div>',
    '      </div>',
    "",
    '      {historyOpen && (',
    '        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex justify-end animate-in fade-in duration-200">',
    '          <div className="w-full max-w-sm bg-slate-900 border-l border-white/10 h-full p-5 flex flex-col shadow-2xl animate-in slide-in-from-right duration-300">',
    '            <div className="flex items-center justify-between pb-4 border-b border-white/10 mb-4">',
    '              <div className="flex items-center gap-2">',
    '                <History className="text-cyan-400" size={18} />',
    '                <h2 className="text-sm font-bold tracking-wide">Calculation History Tape</h2>',
    '              </div>',
    '              <button onClick={() => setHistoryOpen(false)} className="p-1.5 rounded-lg hover:bg-white/10 text-zinc-400 hover:text-white transition-all cursor-pointer">',
    '                <X size={16} />',
    '              </button>',
    '            </div>',
    '            <div className="flex-1 overflow-y-auto space-y-2 pr-1">',
    '              {history.length === 0 ? (',
    '                <div className="text-center py-16 text-zinc-500 space-y-2">',
    '                  <History size={32} className="mx-auto opacity-30" />',
    '                  <p className="text-xs font-mono">No calculations recorded yet.</p>',
    '                </div>',
    '              ) : (',
    '                history.map((item, idx) => (',
    '                  <div key={item.id || idx} onClick={() => recallHistoryItem(item)} className="p-3 rounded-xl bg-white/[0.03] hover:bg-white/[0.07] border border-white/5 hover:border-cyan-500/30 transition-all cursor-pointer group text-right font-mono">',
    '                    <div className="text-[10px] text-zinc-500 flex justify-between items-center mb-1">',
    '                      <span>{item.timestamp || "Recent"}</span>',
    '                      <span className="text-cyan-400 opacity-0 group-hover:opacity-100 transition-opacity text-[9px]">Click to recall ↵</span>',
    '                    </div>',
    '                    <div className="text-xs text-zinc-400 truncate">{item.expression}</div>',
    '                    <div className="text-base font-bold text-white tracking-wide group-hover:text-cyan-300 transition-colors">= {item.result}</div>',
    '                  </div>',
    '                ))',
    '              )}',
    '            </div>',
    '            {history.length > 0 && (',
    '              <button onClick={handleClearHistory} className="mt-4 w-full py-2.5 rounded-xl bg-rose-500/10 hover:bg-rose-500/20 text-rose-300 border border-rose-500/30 text-xs font-semibold flex items-center justify-center gap-2 transition-all cursor-pointer">',
    '                <Trash2 size={14} /> Clear All History',
    '              </button>',
    '            )}',
    '          </div>',
    '        </div>',
    '      )}',
    '    </div>',
    '  );',
    '}'
  ].join('\n');

  const readmeMd = '# ' + safeTitle + '\n\nNeon Cyberpunk Modern Calculator with Memory & History Tape.\n';

  return [
    { path: 'package.json', content: packageJson },
    { path: 'vite.config.js', content: viteConfig },
    { path: 'index.html', content: indexHtml },
    { path: 'server.js', content: serverJs },
    { path: 'src/services/api.js', content: apiJs },
    { path: 'src/index.css', content: indexCss },
    { path: 'src/main.jsx', content: mainJsx },
    { path: 'src/App.jsx', content: appJsx },
    { path: 'README.md', content: readmeMd }
  ];
}

module.exports = { getCalculatorBlueprint };
